### ISSUE TITLE
搜索与permalink

### ISSUE THREAD

**Issue by DefectingCat** [fluid-dev/hexo-theme-fluid#195]
我是将hexo生成的静态文件托管在阿里云的cdn上的。但是遇到个比较特殊的小问题：
**阿里云的oss限制只有带静态后缀名的文件才能够被正常访问。**

例如：通常的关于或者其他分类下的页面，甚至是文章。生成后的链接可能都是这样的`https://www.defectink.com/about/`。通常情况下这样是没有任何问题的（并且about文件夹下是有index.html这个文件的），但对于oss来说，必须要访问`https://www.defectink.com/about/index.html`才能够显示这个页面。

对于oss这个问题，可以配置permalink解决文章的问题。但是例如归档中的“Player”分类，点进去后链接就是`https://www.defectink.com/categories/Player/`。"Player"目录下肯定是有关于这个分类的文章的静态文件的。但是我想显示为：`https://www.defectink.com/categories/Player/index.html`

只有这样才能正常打开。

<hr>

除了上述，由于我配置了permalink才能显示文章。但是搜索功能貌似收到了permalink的影响。

我的permalink配置为`permalink: /defect/:url.html`。搜索能够正常预览

![图片](https://user-images.githubusercontent.com/25033493/78028095-0801a880-7391-11ea-826d-a7923ff2ac78.png)

但是点击匹配的文章后，链接就直接这样了`https://defect/bark-custom-notification-for-apple.html`。正确的链接应该是`https://www.defectink.com/defect/bark-custom-notification-for-apple.html`。

总结就是两个问题：
* 某些页面无法显示完整的静态链接
* 搜索受permalink的影响，域名直接就没了。

其他信息：
fluid：master
node: v12.16.0
插件：all_minifier

**Comment by AimTao** [comment]
开启子目录功能就好啦，看看产品文档------------------ 原始邮件 ------------------发件人: Defectink  <notifications@github.com>发送时间: 2020年3月31日 20:54收件人: fluid-dev/hexo-theme-fluid <hexo-theme-fluid@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[fluid-dev/hexo-theme-fluid] 搜索与permalink (#195)
我是将hexo生成的静态文件托管在阿里云的cdn上的。但是遇到个比较特殊的小问题：
阿里云的oss限制只有带静态后缀名的文件才能够被正常访问。
例如：通常的关于或者其他分类下的页面，甚至是文章。生成后的链接可能都是这样的https://www.defectink.com/about/。通常情况下这样是没有任何问题的（并且about文件夹下是有index.html这个文件的），但对于oss来说，必须要访问https://www.defectink.com/about/index.html才能够显示这个页面。
对于oss这个问题，可以配置permalink解决文章的问题。但是例如归档中的“Player”分类，点进去后链接就是https://www.defectink.com/categories/Player/。"Player"目录下肯定是有关于这个分类的文章的静态文件的。但是我想显示为：https://www.defectink.com/categories/Player/index.html
只有这样才能正常打开。

除了上述，由于我配置了permalink才能显示文章。但是搜索功能貌似收到了permalink的影响。
我的permalink配置为permalink: /defect/:url.html。搜索能够正常预览

但是点击匹配的文章后，链接就直接这样了https://defect/bark-custom-notification-for-apple.html。正确的链接应该是https://www.defectink.com/defect/bark-custom-notification-for-apple.html。
总结就是两个问题：

某些页面无法显示完整的静态链接
搜索受permalink的影响，域名直接就没了。

其他信息：
fluid：master
node: v12.16.0
插件：all_minifier

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fluid-dev/hexo-theme-fluid/issues/195",
"url": "https://github.com/fluid-dev/hexo-theme-fluid/issues/195",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 0x2E** [comment]
https://rook1e.com/p/69ccf529.html#OSS-%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE

**Comment by DefectingCat** [comment]
> 
> 
> 阿里云 oss 配置「子目录首页」后可自动补全 index.html，参考
> https://rook1e.com/p/69ccf529.html#OSS-%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE

感谢。那个搜索是什么问题导致的，有解决方案吗

**Comment by 0x2E** [comment]
> 那个搜索是什么问题导致的，有解决方案吗

似乎是个 bug，还没来得及复现

**Comment by DefectingCat** [comment]
> 
> 
> > 那个搜索是什么问题导致的，有解决方案吗
> 
> 似乎是个 bug，还没来得及复现

[https://www.defectink.com/](https://www.defectink.com/) 我的这个目前在oss上，那个搜索bug还在。如果有需要可以随时过来研究。

**Comment by 0x2E** [comment]
@DefectingCat 这个也算不上 bug 了，你的配置改成 `permalink: defect/:url.html` 就好了。

**Comment by DefectingCat** [comment]
没想到是多一个斜杠导致的，蟹蟹

**Comment by zkqiang** [comment]
已解决，拼接问题
